-- ====== TABELAS PRINCIPAIS ======

-- 1. ESTADIO
CREATE TABLE ESTADIO (
    ID_ESTADIO      NUMBER         PRIMARY KEY,
    NOME            VARCHAR2(100)  NOT NULL,
    LOCALIZACAO     VARCHAR2(150)
);

-- 2. SETOR
CREATE TABLE SETOR (
    ID_SETOR        NUMBER         PRIMARY KEY,
    NOME            VARCHAR2(100)  NOT NULL,
    ID_ESTADIO      NUMBER         NOT NULL,
    CONSTRAINT FK_SETOR_ESTADIO FOREIGN KEY (ID_ESTADIO)
        REFERENCES ESTADIO(ID_ESTADIO)
);

-- 3. ASSENTO
CREATE TABLE ASSENTO (
    ID_ASSENTO      NUMBER         PRIMARY KEY,
    ID_SETOR        NUMBER         NOT NULL,
    CONSTRAINT FK_ASSENTO_SETOR FOREIGN KEY (ID_SETOR)
        REFERENCES SETOR(ID_SETOR)
);

-- 4. EVENTO
CREATE TABLE EVENTO (
    ID_EVENTO       NUMBER         PRIMARY KEY,
    NOME            VARCHAR2(100)  NOT NULL,
    DATA            DATE           NOT NULL,
    ID_ESTADIO      NUMBER         NOT NULL,
    CONSTRAINT FK_EVENTO_ESTADIO FOREIGN KEY (ID_ESTADIO)
        REFERENCES ESTADIO(ID_ESTADIO)
);

-- 5. USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO      NUMBER          PRIMARY KEY,
    NOME            VARCHAR2(100)   NOT NULL,
    USERNAME        VARCHAR2(50)    NOT NULL UNIQUE,
    SENHA           VARCHAR2(100)   NOT NULL
);

-- 6. FUNCIONARIO
CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO  NUMBER          PRIMARY KEY,
    NOME            VARCHAR2(100)   NOT NULL,
    EMAIL           VARCHAR2(100)   UNIQUE,
    SENHA           VARCHAR2(100)   NOT NULL,
    ID_USUARIO      NUMBER,
    CONSTRAINT FK_FUNC_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO(ID_USUARIO)
);

-- 7. INGRESSO
CREATE TABLE INGRESSO (
    ID_INGRESSO     NUMBER          PRIMARY KEY,
    ID_CLIENTE      NUMBER,
    ID_EVENTO       NUMBER          NOT NULL,
    ID_ASSENTO      NUMBER          NOT NULL,
    CONSTRAINT FK_INGRESSO_EVENTO FOREIGN KEY (ID_EVENTO)
        REFERENCES EVENTO(ID_EVENTO),
    CONSTRAINT FK_INGRESSO_ASSENTO FOREIGN KEY (ID_ASSENTO)
        REFERENCES ASSENTO(ID_ASSENTO)
);