CREATE TABLE Estacionamento (
    ID_ESTACIONAMENTO INT PRIMARY KEY,
    DESCRICAO VARCHAR(100),
    CAPACIDADE INT
);

CREATE TABLE POSSUI (
    FK_Estadio_ID_ESTADIO INT,
    FK_Estacionamento_ID_Estacionamento INT,
    PRIMARY KEY (FK_Estadio_ID_ESTADIO, FK_Estacionamento_ID_Estacionamento),
    FOREIGN KEY (FK_Estadio_ID_ESTADIO) REFERENCES Estadio(ID_ESTADIO),
    FOREIGN KEY (FK_Estacionamento_ID_Estacionamento) REFERENCES Estacionamento(ID_ESTACIONAMENTO)
);

CREATE TABLE Estadio (
    ID_ESTADIO INT PRIMARY KEY,
    NOME VARCHAR(100)
);

-- 
CREATE TABLE Setor (
    ID_SETOR INT PRIMARY KEY,
    ID_ESTADIO INT,
    NOME VARCHAR(100),
    FOREIGN KEY (ID_ESTADIO) REFERENCES Estadio(ID_ESTADIO)
);


CREATE TABLE POSSUI_SETOR (
    FK_Estadio_ID_ESTADIO INT,
    FK_Setor_ID_SETOR INT,
    PRIMARY KEY (FK_Estadio_ID_ESTADIO, FK_Setor_ID_SETOR),
    FOREIGN KEY (FK_Estadio_ID_ESTADIO) REFERENCES Estadio(ID_ESTADIO),
    FOREIGN KEY (FK_Setor_ID_SETOR) REFERENCES Setor(ID_SETOR)
);

CREATE TABLE Assento (
    ID_ASSENTO INT PRIMARY KEY,
    ID_SETOR INT,
    FOREIGN KEY (ID_SETOR) REFERENCES Setor(ID_SETOR)
);


CREATE TABLE Evento (
    ID_EVENTO INT PRIMARY KEY,
    NOME VARCHAR(100),
    DATA DATE,
    ID_ESTADIO INT,
    FOREIGN KEY (ID_ESTADIO) REFERENCES Estadio(ID_ESTADIO)
);


CREATE TABLE SEDIA_EVENTOS (
    FK_Estadio_ID_ESTADIO INT,
    FK_Evento_ID_EVENTO INT,
    PRIMARY KEY (FK_Estadio_ID_ESTADIO, FK_Evento_ID_EVENTO),
    FOREIGN KEY (FK_Estadio_ID_ESTADIO) REFERENCES Estadio(ID_ESTADIO),
    FOREIGN KEY (FK_Evento_ID_EVENTO) REFERENCES Evento(ID_EVENTO)
);


CREATE TABLE Usuario_Funcionario (
    ID_USUARIO INT PRIMARY KEY,
    NOME VARCHAR(100),
    USERNAME VARCHAR(50),
    SENHA VARCHAR(100),
    EMAIL VARCHAR(100),
    ID_FUNCIONARIO INT
);


CREATE TABLE Ingresso (
    ID_INGRESSO INT PRIMARY KEY,
    ID_USUARIO INT,
    ID_EVENTO INT,
    ID_ASSENTO INT,
    FK_Usuario_Funcionario INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES Usuario_Funcionario(ID_USUARIO),
    FOREIGN KEY (ID_EVENTO) REFERENCES Evento(ID_EVENTO),
    FOREIGN KEY (ID_ASSENTO) REFERENCES Assento(ID_ASSENTO),
    FOREIGN KEY (FK_Usuario_Funcionario) REFERENCES Usuario_Funcionario(ID_USUARIO)
);
